/control/verbose 0
/run/verbose 1 
/event/verbose 0
/tracking/verbose 0
/gps/verbose 0

# Random seeding needs good care and administration.
#
/run/random/setRandomSeed 12361

# Only a pencil beam shooting in z.
/gps/direction 0 0 1.
# Angular distribution.
#/gps/ang/type iso
#
/gps/particle gamma
/gps/pos/type Point
# lXe volume centred at (0,0,0) and FullZ = 50 cm.
/gps/pos/centre 0. 0. -30. cm
/gps/energy 350 keV
