/control/verbose 1
/run/verbose 1
/event/verbose 1
/tracking/verbose 1

#/vis/scene/create
#/vis/open VRML2FILE
#/vis/open HepRepFile
#/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate

/xe/gun/type Point
/xe/gun/center 0 0 -100 cm
/xe/gun/angtype direction
/xe/gun/direction 0 0 1
/xe/gun/particle mu-
/xe/gun/energytype Mono
/xe/gun/energy 1000. MeV

/process/inactivate Cerenkov
